var ITEMS = [{ id: '', name: 'Jabłka', selected: false},
{ id: '', name: 'Papryka', selected: false},
{ id: '', name: 'Bakłażan', selected: false},
{ id: '', name: 'Szczypiorek', selected: false},
{ id: '', name: 'Natka pietruszki', selected: false},
{ id: '', name: 'Rzodkiewka', selected: false},
{ id: '', name: 'Sałata', selected: false},
{ id: '', name: 'Koperek', selected: false},
{ id: '', name: 'Seler', selected: false},
{ id: '', name: 'Pietruszka', selected: false},
{ id: '', name: 'Cebula', selected: false},
{ id: '', name: 'Ziemniaki', selected: false},
{ id: '', name: 'Kiwi', selected: false},
{ id: '', name: 'Pomarańcze', selected: false},
{ id: '', name: 'Cytryny', selected: false},
{ id: '', name: 'Grejfruty', selected: false},
{ id: '', name: 'Banany', selected: false},
{ id: '', name: 'Gruszki', selected: false},
{ id: '', name: 'bułki hotdogowe', selected: false},
{ id: '', name: 'wafle ryżowe', selected: false},
{ id: '', name: 'groszek ptysiowy', selected: false},
{ id: '', name: 'mąka', selected: false},
{ id: '', name: 'cukier', selected: false},
{ id: '', name: 'makaron', selected: false},
{ id: '', name: 'Ryż', selected: false},
{ id: '', name: 'Kasza', selected: false},
{ id: '', name: 'przecier pomidorowy w kartoniku', selected: false},
{ id: '', name: 'pomidory w puszce całe', selected: false},
{ id: '', name: 'ketchup', selected: false},
{ id: '', name: 'kawa', selected: false},
{ id: '', name: 'masło', selected: false},
{ id: '', name: 'śmietana', selected: false},
{ id: '', name: 'jogurty', selected: false},
{ id: '', name: 'serek wiejski', selected: false},
{ id: '', name: 'ser ulubiony', selected: false},
{ id: '', name: 'ser śmietankowy', selected: false},
{ id: '', name: 'jajka', selected: false},
{ id: '', name: 'makrela', selected: false},
{ id: '', name: 'sałatki', selected: false},
{ id: '', name: 'pierogi', selected: false},
{ id: '', name: 'Ser żółty', selected: false},
{ id: '', name: 'wędliny', selected: false},
{ id: '', name: 'kurczak', selected: false},
{ id: '', name: 'mięso', selected: false},
{ id: '', name: 'mrożonki', selected: false},
{ id: '', name: 'pizza', selected: false},
{ id: '', name: 'woda', selected: false},
{ id: '', name: 'piwo', selected: false},
{ id: '', name: 'Antyperspirant', selected: false},
{ id: '', name: 'Mydło', selected: false},
{ id: '', name: 'Szampon', selected: false},
{ id: '', name: 'Szczoteczki do zębów', selected: false},
{ id: '', name: 'Pasta do zębów', selected: false},
{ id: '', name: 'Worki', selected: false},
{ id: '', name: 'Ściereczki', selected: false},
{ id: '', name: 'Gąbki', selected: false},
{ id: '', name: 'Plyn do naczyń', selected: false},
{ id: '', name: 'Gazety', selected: false}];
